noLoopMax: noLoopMax.cpp
	g++ -std=c++11 noLoopMax.cpp -o noLoopMax
stackFromQueues: stackFromQueues.cpp
	g++ -std=c++11 stackFromQueues.cpp -o stackFromQueues
recurLLCount: recurLLCount.cpp LinkedList.cpp
	g++ -std=c++11 recurLLCount.cpp LinkedList.cpp -o recurLLCount
clean:
	rm *.o main
